<!--
title: Quick Trick: Catching a Perl 6 warning
link: http://www.learningraku.com/2018/01/10/quick-trick-catching-a-perl-6-warning/
author: brian
post_id: 419
date: 2018-01-10 11:17:32
post_name: quick-trick-catching-a-perl-6-warning
status: publish
type: post
categories: quick-tricks testing
tags: 
-->


While testing <A href="https://github.com/briandfoy/perl6-file-find">a module</a> I wanted to check that a deprecation warning shows up. <A href="https://docs.perl6.org/routine/warn">Warnings are a special sort of exception</a> that you can catch in a <code>CONTROL</code> block. <!--more-->

<div class="image center">
<div>
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/melystu/37292580974/in/photolist-YPqe53-nUC4oD-evv5mJ-Htsmd-H6opx-pyKgLb-aA77Ex-7FGuyD-5a1w8K-NZQ4C-RovuiA-6Pf16K-BDnfpU-qiwpvR-4WCtFb-dJ5pDe-b1Ejyk-TCH4WL-7mupFc-2T7pK-aNbbmk-vZbnP-9xsTYB-4SpkrJ-AWPMt-sAAcT-rdRWP5-a2p3MT-ouoRCq-qkS83i-6mZr18-aXtfkT-Two3N9-a2p41c-jJzAYb-71pDf-HFx1uf-Krr1E-cisdqw-9fH8E1-jWWBuX-8HrBUk-oGUeeR-SYSxjh-VV8NrT-8hGBuL-6qxFCb-eys5Ps-neD4M6-YBaPJK" title="Warning!"><img src="https://farm5.staticflickr.com/4483/37292580974_e11f1d4b14.jpg" width="500" height="347" alt="Warning!"></a>
</div>
</div>

In my test file I add a <A href="https://docs.perl6.org/language/phasers#CONTROL">CONTROL phaser</a>. This catches the action of block exiting things including <code>return</code>, <code>fail</code>, <code>redo</code>, <code>next</code>, <code>last</code>, <code>take</code>, and in this case, <code>warn</code>:

<pre class="brush:plain">
{ # with forced find to Not work recursive
CONTROL {
	my $label = ':recursive warns about deprecation';
	when CX::Warn { like $_.message, /deprecated/, $label; }
	default       { fail( $label ); }
	}
my $res = find(:dir&lt;t/dir1>, :name&lt;file.bar>, recursive => False);
is $res.elems, 1, 'name with a string';
}
</pre>

You won't catch these in a normal <code>CATCH</code> block:

<pre class="brush:plain">
sub foow { warn "This is a warning" }
sub food { die  "This is a death" }

{
CONTROL {
	when CX::Warn { put "Caught warning in CONTROL" }
	}
foow();
}


try {
CATCH {
	when CX::Warn  { put "Caught warning in CATCH" }
	when  X::AdHoc { put "Caught death in CATCH" }
	default { put "Caught {$_.^name} with {$_.message}" }
	}
foow();
food();
}
</pre>

The output shows that the <code>CONTROL</code> caught the warning from the first call but the <code>CATCH</code> let it pass through in the second:

<pre class="brush:plain">
Caught warning in CONTROL
Caught death in CATCH
This is a warning
  in sub foow at /Users/brian/Desktop/test.p6 line 5
</pre>
